[tool.poetry]
name = "casino"
version = "0.2.0.post7.dev0+3e6fe06"
description = "Casino enables fast probabilistic modelling"
authors = ["Adolph Vogel <ajvogel@gmail.com>"]
license = "MIT"
readme = "README.md"
include = ['casino/*.so']




